### PR TITLE
Fixing new domoticz blinds protocol.

### PR DESCRIPTION
**Pull request by juantecnico**
Fix of new domoticz blinds protocol

### CODE REVIEW

**Comment by juantecnico** [comment]
Fix of new domoticz blinds protocol

**Review by enesbcs — COMMENTED** [review]
Seems ok, but what about supporting older firmwares?

**Comment by juantecnico** [comment]
Its seem that in beta 14542 there was a change in blinds system.
¿Can be possible to read domoticz version in plugin and make a simple if stament if necesary?
 PD, i´m not programmer, but have some knowledge.

**Comment by enesbcs** [comment]
How about this alternative form?
'''
            if cmnd == "on" or cmnd == "open":
             scmd = "close"
            elif cmnd == "off" or cmnd == "close":
             scmd = "open"
           else:
            if cmnd == "on" or open":
             scmd = "open"
            elif cmnd == "off" or cmnd == "close":
             scmd = "close"            
'''

**Comment by juantecnico** [comment]
> How about this alternative form? ''' if cmnd == "on" or cmnd == "open": scmd = "close" elif cmnd == "off" or cmnd == "close": scmd = "open" else: if cmnd == "on" or open": scmd = "open" elif cmnd == "off" or cmnd == "close": scmd = "close" '''

Seems more clear than my option.

**Comment by josemi73** [comment]
Hi. Are you going to commit the changes? I did it locally in plugin.py, and it is working now. Not only roller shutter, but also in percentage part of code.
Besides, there is a new type of blind (blinds + stop) in Domoticz, I do not know if changing in plugin.py is needed.

**Comment by josemi73** [comment]
@enesbcs 
What I mean that two switch devices are created by every Shelly (13 and 15) for -pos and -roller:

switch_before

Now there is a new device (21) named blinds+stop, I think it is not necessary that two devices be created.

switchtypeval

Regards

**Comment by josemi73** [comment]
Thank you!!
Plugin is already working properly.

**Comment by Epik77** [comment]
sorry but roller button not works
blinds_roller

while the position button reversing the logic works correctly.

blinds_position


I also cleared the browser cache, removed the buttons and let the system detect them

I think this type of button should also be fixed.

thank's

**Comment by enesbcs** [comment]
Waiting for the PR

**Comment by Epik77** [comment]
Hi,
thank's Argenlos
By modifying the file, the shutters work correctly (without reversing the logic)
if you can apply it to the version we keep the plugin updated :-)
thanks to all the developers :-)

**Pull request merged**
