### PR TITLE
Added Shelly Sense Motion sensor.

### PR DESCRIPTION
**Pull request by blazoncek**
Removed Shelly HT and Shelly Sense (temeperature & humidity) dependency for custom ESP8266/ESP32 sensors emulating Shellies.

I have created custom ESP8266/ESP32 sketch that uses Shelly MQTT API but uses shellies/ESP-XXXXX instead of shellies/shellysense-XXXXX (or shellies/shellyht-XXXXX) for sensors.

### CODE REVIEW

**Comment by enesbcs** [comment]
Interesting, but why do you use Selector switch type for a binary motion sensor?

**Comment by blazoncek** [comment]
Good question. :)
It was my bad looking at [https://www.domoticz.com/wiki/Developing_a_Python_plugin#Available_Device_Types](url). It can also be regular Switch. It is the Switchtype that matters. Works in both cases.

**Comment by enesbcs** [comment]
Removed Shelly HT and Shelly Sense is generally not a good idea... in this structure the ShellyFlood and Shelly Smoke will also fit for these condition "(len(mqttpath)>3) and (mqttpath[2] == "sensor") and (mqttpath[3] in ['temperature','humidity','battery'])" which is incorrect, as they are not providing humidity. Maybe if i place shellysmoke and shellyflood before your conditions, than it will work as it should. And for the record "motion" can be added to the flood and smoke handler.

**Comment by blazoncek** [comment]
Great. I understand the implications. Since I don't own shellyflood or HT I didn't know that.
I just looked at shelly mqtt api and adjusted accordingly.
Thanks for pointing it out. I'll dig deeper into your code when I get time to add other features (like custom MQTT base (shellies), multiple temperature sensors and such).

**Comment by enesbcs** [comment]
All right. I also do not own shellyflood or HT but after reviewing the code, i've fixed it. (at least i hope) :)

**Comment by blazoncek** [comment]
Sorry to bother you, but I have made another change (in my fork) regarding custom ESP modules using shellies MQTT protocol.
Before I make a pull request could you look at the code? I am building an ESP with multiple DS18S20 temperature sensors (amongst other things) and have figured out how to implement them using Shelly_MQTT plugin.
I know it is not compatible with existing shellies, but so far does not interfere with the existing code (as my previous change did). The topic is shellies/esp-xxxxx/temperature/y (where y represents temperature sensor (0-9)). The code for the ESP is in my other repo.
And may I use email for more in-depth discussion?

**Comment by enesbcs** [comment]
I really appreciate your work, but sorry, this plugin made only for Shelly device mqtt translation.

**Comment by blazoncek** [comment]
What a pity. :)
This plugin has such a potential to become so much more. But I understand you.
I hope you don't mind if I continue on my fork deviating from "Shelly only" plugin.

**Comment by enesbcs** [comment]
The code base is already big enough, instead of growing it, it has to be compacted as possible.

**Pull request merged**
